import { existsSync } from 'node:fs'
import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import {
  cancel,
  confirm,
  intro,
  isCancel,
  outro,
  password,
  select,
  spinner,
  text,
} from '@clack/prompts'
import {
  type AnimaNetwork,
  NETWORK_CHAIN_ID,
  NETWORK_RPC,
  agentPaths,
  defineConfig,
  generateAgentWallet,
  placeholderAgentId,
  saveKeystore,
} from '@s0nderlabs/anima-core'
import { writeConfigTs } from '../config/render'

export async function runInit(opts?: { cwd?: string }): Promise<void> {
  const cwd = opts?.cwd ?? process.cwd()
  const configPath = join(cwd, 'anima.config.ts')

  intro('anima init')

  if (existsSync(configPath)) {
    const ok = await confirm({
      message: `${configPath} already exists. Overwrite?`,
      initialValue: false,
    })
    if (isCancel(ok) || !ok) {
      cancel('Aborted.')
      return
    }
  }

  const network = (await select({
    message: 'Which 0G network?',
    options: [
      { value: '0g-mainnet' as AnimaNetwork, label: '0G mainnet (16661)' },
      { value: '0g-testnet' as AnimaNetwork, label: '0G Galileo testnet (16602)' },
    ],
    initialValue: '0g-mainnet' as AnimaNetwork,
  })) as AnimaNetwork

  if (isCancel(network)) {
    cancel('Aborted.')
    return
  }

  const subname = await text({
    message: 'Subname under anima.0g (leave blank to pick later)',
    placeholder: 'e.g. alice',
    validate: v => {
      if (!v) return undefined
      if (!/^[a-z0-9](?:[a-z0-9-]{1,30}[a-z0-9])?$/.test(v))
        return 'Subnames: 3-32 chars, lowercase a-z, 0-9, hyphens (not leading/trailing).'
      return undefined
    },
  })
  if (isCancel(subname)) {
    cancel('Aborted.')
    return
  }

  const pass = await password({
    message: 'Choose a passphrase for the agent keystore (min 8 chars)',
    validate: v => (v && v.length >= 8 ? undefined : 'Min 8 chars required.'),
  })
  if (isCancel(pass)) {
    cancel('Aborted.')
    return
  }

  const passConfirm = await password({
    message: 'Confirm passphrase',
  })
  if (isCancel(passConfirm)) {
    cancel('Aborted.')
    return
  }
  if (pass !== passConfirm) {
    cancel('Passphrases do not match.')
    return
  }

  const s = spinner()
  s.start('Generating agent EOA')
  const { privkeyHex, address } = generateAgentWallet()
  const agentId = placeholderAgentId(address)
  const paths = agentPaths.agent(agentId)

  await mkdir(paths.dir, { recursive: true })
  await saveKeystore(paths.keystore, privkeyHex, pass)
  s.stop(`Agent EOA ${address}`)

  const s2 = spinner()
  s2.start('Writing anima.config.ts')
  const cfg = defineConfig({
    identity: { iNFT: null },
    network,
    storage: { network },
    brain: { provider: null, model: null },
    plugins: ['onchain', 'comms', 'system'],
    tools: {},
    imports: { claudeCode: true },
  })

  await writeConfigTs(configPath, cfg, {
    header: '// Regenerated by `anima init`. Edit freely; type-safe.',
    subname: subname || null,
  })
  s2.stop(`Wrote ${configPath}`)

  outro(
    [
      '',
      `  agent id   ${agentId}`,
      `  agent EOA  ${address}`,
      `  network    ${network} (${NETWORK_RPC[network]})`,
      `  chain id   ${NETWORK_CHAIN_ID[network]}`,
      `  keystore   ${paths.keystore}`,
      '',
      'Next: fund the agent EOA with some 0G for gas, then run `anima` to chat.',
    ].join('\n'),
  )
}
