import {
  PAIRING_ALPHABET,
  PAIRING_CODE_LENGTH,
  PairingStore,
  agentPaths,
  iNFTAgentId,
} from '@s0nderlabs/anima-core'
import { getAddress } from 'viem'
import { findAndLoadConfig } from '../config/load'
import { SandboxClient } from '../sandbox/client'
import { loadOrPickOperatorSigner } from './init/operator-picker'

export interface RunPairingApproveOpts {
  platform: string
  code: string
}

export async function runPairingApprove(opts: RunPairingApproveOpts): Promise<void> {
  const normalized = opts.code.toUpperCase().trim()
  if (normalized.length !== PAIRING_CODE_LENGTH) {
    console.error(
      `Invalid pairing code: expected ${PAIRING_CODE_LENGTH} characters, got ${normalized.length}`,
    )
    process.exit(1)
  }
  for (const ch of normalized) {
    if (!PAIRING_ALPHABET.includes(ch)) {
      console.error(`Invalid pairing code: contains '${ch}' which is not in the pairing alphabet`)
      process.exit(1)
    }
  }

  const loaded = await findAndLoadConfig()
  if (!loaded) {
    console.error('No anima.config.ts found. Run `anima init` first.')
    process.exit(1)
  }
  const { config } = loaded
  if (!config.identity.iNFT) {
    console.error('Config has no iNFT. Run `anima init` first.')
    process.exit(1)
  }

  // v0.24.4: sandbox-deployed agents need their pairing dir reached over the
  // signed admin endpoint; the local PairingStore on the host won't see codes
  // generated by the container. Mirror the autotopup-tick / profile-key
  // sandbox branch in admin-autotopup-tick.ts.
  if (config.deployTarget === 'sandbox' && config.sandbox?.endpoint && config.sandbox.id) {
    const signer = await loadOrPickOperatorSigner({
      network: config.network,
      hint: config.operator,
    })
    if (!signer) {
      console.error('failed to load operator signer (cancelled or no key)')
      process.exit(1)
    }
    const operatorAccount = await signer.account()
    const client = new SandboxClient({
      endpoint: config.sandbox.endpoint,
      sandboxId: config.sandbox.id,
      operator: operatorAccount,
    })
    try {
      const result = await client.approvePairing(opts.platform, normalized)
      if (!result.ok) {
        if (result.reason === 'locked-out') {
          console.error(
            `Platform '${opts.platform}' is locked out due to repeated bad codes. Wait 1 hour and try again.`,
          )
          process.exit(1)
        }
        console.error(`Code ${normalized} not found in pending list. Maybe it expired (1h TTL).`)
        process.exit(1)
      }
      console.log(
        `✓ Approved on ${opts.platform}: id=${result.userId}${
          result.userName ? ` (@${result.userName})` : ''
        }`,
      )
      console.log('The user can now DM the bot. Their next message will be processed.')
      return
    } catch (e) {
      console.error(`pairing-approve failed: ${(e as Error).message.slice(0, 240)}`)
      process.exit(1)
    }
  }

  // Local deploy: operate directly on the host's PairingStore (same path as
  // the daemon process when ANIMA_FORCE_EMBEDDED or local-mode chat.tsx).
  const inftContract = getAddress(config.identity.iNFT.contract) as `0x${string}`
  const tokenId = BigInt(config.identity.iNFT.tokenId)
  const agentId = iNFTAgentId({ contractAddress: inftContract, tokenId })
  const dir = agentPaths.agent(agentId).pairingDir
  const store = new PairingStore({ dir })

  const result = store.approveCode(opts.platform, normalized)
  if (!result) {
    if (store.isLockedOut(opts.platform)) {
      console.error(
        `Platform '${opts.platform}' is locked out due to repeated bad codes. Wait 1 hour and try again.`,
      )
      process.exit(1)
    }
    console.error(`Code ${normalized} not found in pending list. Maybe it expired (1h TTL).`)
    process.exit(1)
  }

  console.log(
    `✓ Approved on ${opts.platform}: id=${result.userId}${
      result.userName ? ` (@${result.userName})` : ''
    }`,
  )
  console.log('The user can now DM the bot. Their next message will be processed.')
}
