import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { cancel, intro, isCancel, note, outro, password, spinner } from '@clack/prompts'
import {
  type AnimaNetwork,
  type EncryptedKeystore,
  NETWORK_CHAIN_ID,
  agentPaths,
  decryptKey,
  defineConfig,
  explorerTokenUrl,
  iNFTAgentId,
  networkFromChainId,
  restoreKeystoreFromStorage,
} from '@s0nderlabs/anima-core'
import { type Address, bytesToHex } from 'viem'
import { privateKeyToAccount } from 'viem/accounts'
import { writeConfigTs } from '../config/render'

interface ParsedRef {
  network: AnimaNetwork
  contract: Address
  tokenId: bigint
}

function parseRef(ref: string): ParsedRef {
  const parts = ref.split(':')
  if (parts.length === 4 && parts[0] === 'eip155') {
    const chainId = Number(parts[1])
    const contract = parts[2] as Address
    const tokenId = BigInt(parts[3]!)
    const network = networkFromChainId(chainId)
    if (!network) {
      const known = Object.values(NETWORK_CHAIN_ID).join(' or ')
      throw new Error(`Unknown chain id ${chainId} (expected ${known})`)
    }
    return { network, contract, tokenId }
  }
  if (parts.length === 3 && (parts[0] === '0g-mainnet' || parts[0] === '0g-testnet')) {
    return {
      network: parts[0] as AnimaNetwork,
      contract: parts[1] as Address,
      tokenId: BigInt(parts[2]!),
    }
  }
  throw new Error(
    `Unrecognized iNFT ref '${ref}'. Expected 'eip155:<chain>:<contract>:<tokenId>' or '0g-mainnet:<contract>:<tokenId>'.`,
  )
}

export async function runRestore(opts: { ref: string; cwd?: string }): Promise<void> {
  const cwd = opts.cwd ?? process.cwd()
  const configPath = join(cwd, 'anima.config.ts')

  intro('anima restore')

  let parsed: ParsedRef
  try {
    parsed = parseRef(opts.ref)
  } catch (e) {
    cancel((e as Error).message)
    return
  }

  const s1 = spinner()
  s1.start(`Fetching iNFT #${parsed.tokenId} on ${parsed.network}`)

  let encryptedBytes: Uint8Array
  let operatorAddress: Address
  try {
    const downloaded = await restoreKeystoreFromStorage({
      network: parsed.network,
      contractAddress: parsed.contract,
      tokenId: parsed.tokenId,
    })
    if (!downloaded) {
      s1.stop('keystore slot is unset or predates storage-backed recovery')
      note(
        [
          'This iNFT does not have an encrypted keystore uploaded to 0G Storage.',
          'Either the slot still holds a bootstrap placeholder, or the agent was',
          'minted before the recovery path was live. If you have a local keystore,',
          'copy it to ~/.anima/agents/<id>/keystore.json manually.',
        ].join('\n'),
        'cannot restore',
      )
      return
    }
    encryptedBytes = downloaded.encryptedBytes
    operatorAddress = downloaded.owner
    s1.stop(`fetched ${encryptedBytes.byteLength} bytes from 0G Storage`)
  } catch (e) {
    s1.stop(`fetch failed: ${(e as Error).message}`)
    return
  }

  const pass = await password({
    message: 'Passphrase for the agent keystore',
    validate: v => (v && v.length >= 1 ? undefined : 'Required.'),
  })
  if (isCancel(pass)) {
    cancel('Aborted.')
    return
  }

  let keystore: EncryptedKeystore
  let privkeyHex: `0x${string}`
  let agentAddress: Address
  try {
    keystore = JSON.parse(new TextDecoder().decode(encryptedBytes)) as EncryptedKeystore
    const privkey = decryptKey(keystore, pass)
    privkeyHex = bytesToHex(privkey)
    agentAddress = privateKeyToAccount(privkeyHex).address
  } catch (e) {
    cancel(`decrypt failed: ${(e as Error).message}. Wrong passphrase or corrupted keystore.`)
    return
  }

  const agentId = iNFTAgentId({ contractAddress: parsed.contract, tokenId: parsed.tokenId })
  const paths = agentPaths.agent(agentId)
  await mkdir(paths.dir, { recursive: true })
  await writeFile(paths.keystore, JSON.stringify(keystore, null, 2), 'utf8')

  const cfg = defineConfig({
    identity: {
      iNFT: {
        contract: parsed.contract,
        tokenId: parsed.tokenId.toString(),
        network: parsed.network,
      },
      operator: operatorAddress,
      agent: agentAddress,
    },
    network: parsed.network,
    storage: { network: parsed.network },
    brain: { provider: null, model: null },
    plugins: ['onchain', 'comms', 'system'],
    tools: {},
    imports: { claudeCode: true },
  })
  await writeConfigTs(configPath, cfg, {
    header: '// Regenerated by `anima restore`. Edit freely; type-safe.',
    subname: null,
  })

  outro(
    [
      '',
      `  agent id   ${agentId}`,
      `  agent EOA  ${agentAddress}`,
      `  operator   ${operatorAddress}`,
      `  iNFT       #${parsed.tokenId.toString()} at ${parsed.contract}`,
      `             ${explorerTokenUrl(parsed.network, parsed.contract, parsed.tokenId)}`,
      `  keystore   ${paths.keystore}`,
      '',
      'Next: `anima` to chat, or `anima topup --compute 5` if ledger is dry.',
    ].join('\n'),
  )
}
