import { describe, expect, test } from 'bun:test'
import { encryptToPubkey, generateBootstrapKeypair } from '@s0nderlabs/anima-core'
import { type Hex, hexToBytes } from 'viem'
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts'
import {
  type ProvisionRequest,
  adminTickHash,
  approvalResponseHash,
  chatMessageHash,
  provisionMessageHash,
  verifyAdminTickSig,
  verifyApprovalSig,
  verifyChatSig,
  verifyProvisionSig,
} from './auth'
import type { RuntimeConfig } from './runtime'

const INFT_REF = { contract: '0x9e71d79f06f956d4d2666b5c93dafab721c84721', tokenId: '6' } as const

const CONFIG: RuntimeConfig = {
  network: '0g-mainnet',
  brain: { provider: '0x0000000000000000000000000000000000000111', model: 'glm-5' },
  identity: {
    iNFT: INFT_REF,
    agent: '0x1111111111111111111111111111111111111111',
  },
}

async function sign(operatorPriv: Hex, hash: Hex): Promise<Hex> {
  const account = privateKeyToAccount(operatorPriv)
  return account.signMessage({ message: { raw: hash } })
}

function makeRequest(): { req: ProvisionRequest; bootstrapPub: Hex; agentPriv: Hex } {
  const bootstrap = generateBootstrapKeypair()
  const agentPriv = generatePrivateKey()
  const envelope = encryptToPubkey({
    recipientPubkey: bootstrap.pubkeyHexCompressed,
    plaintext: hexToBytes(agentPriv),
  })
  return {
    req: {
      envelope,
      operatorAddress: '0x0000000000000000000000000000000000000000',
      iNFTRef: INFT_REF,
      config: CONFIG,
      ts: Date.now(),
    },
    bootstrapPub: bootstrap.pubkeyHexCompressed,
    agentPriv,
  }
}

describe('provision sig verification', () => {
  test('roundtrip: operator signs the digest, harness verifies', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    req.operatorAddress = operator

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(operatorPriv, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects when operatorAddress does not match expectedOperator', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operatorPriv = generatePrivateKey()
    const wrongOperatorPriv = generatePrivateKey()
    req.operatorAddress = privateKeyToAccount(operatorPriv).address

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(operatorPriv, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: privateKeyToAccount(wrongOperatorPriv).address,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('operator-mismatch')
  })

  test('rejects when signature was generated by a different key', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operatorPriv = generatePrivateKey()
    const attackerPriv = generatePrivateKey()
    req.operatorAddress = privateKeyToAccount(operatorPriv).address

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(attackerPriv, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('sig-mismatch')
  })

  test('rejects sig over a different bootstrap pubkey (replay-against-other-harness)', async () => {
    const { req } = makeRequest()
    const operatorPriv = generatePrivateKey()
    req.operatorAddress = privateKeyToAccount(operatorPriv).address

    const otherGatewayPub = generateBootstrapKeypair().pubkeyHexCompressed
    const realGatewayPub = generateBootstrapKeypair().pubkeyHexCompressed

    const hashForOther = provisionMessageHash(req, otherGatewayPub)
    const sig = await sign(operatorPriv, hashForOther)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: realGatewayPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('sig-mismatch')
  })

  test('rejects sig if config mutated between sign and verify', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operatorPriv = generatePrivateKey()
    req.operatorAddress = privateKeyToAccount(operatorPriv).address
    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(operatorPriv, hash)
    // Tamper with config after signing.
    req.config = { ...req.config, brain: { ...req.config.brain, model: 'evil-model' } }
    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('sig-mismatch')
  })

  test('rejects stale ts', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operatorPriv = generatePrivateKey()
    req.operatorAddress = privateKeyToAccount(operatorPriv).address
    const now = 1_000_000_000_000
    req.ts = now - 10 * 60 * 1000

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(operatorPriv, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
      now,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('ts-stale')
  })

  test('rejects ts too far in the future', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operatorPriv = generatePrivateKey()
    req.operatorAddress = privateKeyToAccount(operatorPriv).address
    const now = 1_000_000_000_000
    req.ts = now + 5 * 60 * 1000

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(operatorPriv, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
      now,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('ts-future')
  })

  test('survives JSON.stringify→parse roundtrip when config carries undefined-valued optional fields', async () => {
    // Regression for the v0.15.2 → v0.15.3 sandbox-upgrade sig-mismatch:
    // CLI builds RuntimeConfig with `promptAppend: undefined` (caller didn't
    // set it). It signs the in-memory config, JSON.stringify drops the field
    // on the wire, and the harness's parsed config has no `promptAppend` key.
    // If `stableStringify` hashed `undefined` as the literal text "undefined"
    // for the CLI but skipped the key for the harness, hashes differed.
    const { req, bootstrapPub } = makeRequest()
    const operatorPriv = generatePrivateKey()
    req.operatorAddress = privateKeyToAccount(operatorPriv).address
    req.config = {
      ...req.config,
      // biome-ignore lint/suspicious/noExplicitAny: deliberately exercising the optional-undefined path
      promptAppend: undefined as any,
      // biome-ignore lint/suspicious/noExplicitAny: same
      plugins: undefined as any,
    }
    const hashCli = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(operatorPriv, hashCli)

    // Simulate the wire roundtrip the harness sees.
    const reqOnWire = JSON.parse(JSON.stringify(req)) as ProvisionRequest
    expect((reqOnWire.config as unknown as Record<string, unknown>).promptAppend).toBeUndefined()
    expect(Object.hasOwn(reqOnWire.config, 'promptAppend')).toBe(false)

    const r = await verifyProvisionSig({
      request: reqOnWire,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(true)
  })
})

describe('chat sig verification', () => {
  test('roundtrip', async () => {
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    const ts = Date.now()
    const hash = chatMessageHash('hello', ts, 'sbx-1')
    const sig = await sign(operatorPriv, hash)
    const r = await verifyChatSig({
      message: 'hello',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects signature from a different sandbox', async () => {
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    const ts = Date.now()
    const sigForOther = await sign(operatorPriv, chatMessageHash('hello', ts, 'sbx-other'))
    const r = await verifyChatSig({
      message: 'hello',
      ts,
      sandboxId: 'sbx-real',
      signature: sigForOther,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(false)
  })
})

describe('admin tick sig verification (v0.21.9)', () => {
  test('roundtrip for autotopup-tick action', async () => {
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    const ts = Date.now()
    const hash = adminTickHash({ action: 'autotopup-tick', ts, sandboxId: 'sbx-enigma' })
    const sig = await sign(operatorPriv, hash)
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-enigma',
      signature: sig,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects sig for a different action (cross-action replay)', async () => {
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    const ts = Date.now()
    const sigForOther = await sign(
      operatorPriv,
      adminTickHash({ action: 'sync-trigger', ts, sandboxId: 'sbx-1' }),
    )
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-1',
      signature: sigForOther,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(false)
    if (r.ok) throw new Error('unreachable')
    expect(r.reason).toBe('sig-mismatch')
  })

  test('rejects sig for a different sandbox', async () => {
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    const ts = Date.now()
    const sigForOther = await sign(
      operatorPriv,
      adminTickHash({ action: 'autotopup-tick', ts, sandboxId: 'sbx-other' }),
    )
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-real',
      signature: sigForOther,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(false)
  })

  test('rejects expired ts (>5 min stale)', async () => {
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    const ts = Date.now() - 6 * 60 * 1000
    const hash = adminTickHash({ action: 'autotopup-tick', ts, sandboxId: 'sbx-1' })
    const sig = await sign(operatorPriv, hash)
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(false)
    if (r.ok) throw new Error('unreachable')
    expect(r.reason).toBe('ts-stale')
  })

  test('rejects future-skewed ts (>1 min ahead)', async () => {
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    const ts = Date.now() + 2 * 60 * 1000
    const hash = adminTickHash({ action: 'autotopup-tick', ts, sandboxId: 'sbx-1' })
    const sig = await sign(operatorPriv, hash)
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(false)
    if (r.ok) throw new Error('unreachable')
    expect(r.reason).toBe('ts-future')
  })
})

describe('approval sig verification', () => {
  test('roundtrip', async () => {
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    const ts = Date.now()
    const hash = approvalResponseHash({
      approvalId: 'apv-1',
      decision: 'allow',
      ts,
      sandboxId: 'sbx-1',
    })
    const sig = await sign(operatorPriv, hash)
    const r = await verifyApprovalSig({
      approvalId: 'apv-1',
      decision: 'allow',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects mismatched decision', async () => {
    const operatorPriv = generatePrivateKey()
    const operator = privateKeyToAccount(operatorPriv).address
    const ts = Date.now()
    const sig = await sign(
      operatorPriv,
      approvalResponseHash({ approvalId: 'apv-1', decision: 'allow', ts, sandboxId: 'sbx-1' }),
    )
    const r = await verifyApprovalSig({
      approvalId: 'apv-1',
      decision: 'deny',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operator,
    })
    expect(r.ok).toBe(false)
  })
})
