import type { Address, Chain, PublicClient, WalletClient } from 'viem'
import type { Account } from 'viem/accounts'
import type { AnimaNetwork } from '../config'

/**
 * The operator is the human (or organization) behind an anima agent. Per
 * project-anima.md section 22.1, the operator's wallet is what OWNS the
 * ERC-7857 iNFT. A separate agent EOA (generated by `anima init`) is a
 * pay-for-infra key that the operator approves via `setApprovalForAll`.
 *
 * Operator signing material can come from many sources (MetaMask via
 * WalletConnect, hardware wallet, macOS keychain for dev, env var, raw
 * keystore file, etc.). This interface is the abstraction a caller uses
 * without caring which source is behind it.
 */
export interface OperatorSigner {
  /** Source label for logs + UI ("keychain:dev.deployer", "walletconnect:<peer>", ...). */
  readonly source: string
  /** Operator's on-chain address. Becomes the iNFT owner. */
  address(): Promise<Address>
  /** viem account for composing with other clients. */
  account(): Promise<Account>
  /** A wallet client bound to `network` that signs from the operator's address. */
  walletClient(network: AnimaNetwork): Promise<WalletClient>
  /** A public client for the same network (reads only). */
  publicClient(network: AnimaNetwork): Promise<PublicClient>
  /** Chain metadata as viem Chain, per network. */
  chain(network: AnimaNetwork): Chain
}
